# Generated by Django 5.0.7 on 2024-07-29 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=100)),
                ("staff_id", models.CharField(max_length=100)),
                ("duty_card_no", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_name", models.CharField(max_length=100)),
                ("pick_up_time", models.TimeField()),
                ("drop_off_time", models.TimeField()),
                ("shift_time", models.TimeField()),
                ("head_count", models.IntegerField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="duty.driver",
                    ),
                ),
            ],
        ),
    ]
