# Generated by Django 5.0.7 on 2024-07-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0006_driverstaffdata_dutydriver_alter_driver_staff"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverStaffData",
        ),
        migrations.DeleteModel(
            name="DutyDriver",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="staff",
        ),
        migrations.AddField(
            model_name="driver",
            name="staff_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
