# Generated by Django 5.0.7 on 2024-07-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DutyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=100)),
                ("staff_id", models.CharField(max_length=100)),
                ("duty_card_no", models.CharField(max_length=100)),
                ("route_name", models.CharField(max_length=100)),
                ("pick_up_time", models.TimeField()),
                ("drop_off_time", models.TimeField()),
                ("shift_time", models.TimeField()),
                ("head_count", models.IntegerField()),
            ],
        ),
    ]
