# Generated by Django 5.0.7 on 2024-12-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BreakdownReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_datetime", models.DateTimeField(auto_now_add=True)),
                ("breakdown_datetime", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("route_number", models.CharField(max_length=100)),
                ("trip_work_order", models.CharField(max_length=100)),
                ("passengers_involved", models.PositiveIntegerField()),
                ("ek_staff_numbers", models.TextField(blank=True, null=True)),
                ("non_ek_passenger_details", models.TextField(blank=True, null=True)),
                ("injured_passengers", models.PositiveIntegerField(default=0)),
                ("action_taken_for_injured", models.TextField(blank=True, null=True)),
                ("vehicle_damage", models.BooleanField(default=False)),
                ("driver_name", models.CharField(max_length=100)),
                ("driver_id", models.CharField(max_length=100)),
                ("driver_shift", models.CharField(max_length=100)),
                ("breakdown_description", models.TextField()),
                ("ek_vehicles_involved", models.PositiveIntegerField(default=0)),
                ("vehicle_make_plate", models.CharField(max_length=100)),
                (
                    "replacement_vehicle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reported_to_person", models.CharField(max_length=100)),
                ("reported_datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="DelayData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("route", models.CharField(max_length=255)),
                (
                    "in_out",
                    models.CharField(
                        choices=[("IN", "IN"), ("OUT", "OUT")], max_length=50
                    ),
                ),
                ("std", models.TimeField()),
                ("atd", models.TimeField()),
                ("sta", models.TimeField()),
                ("ata", models.TimeField()),
                ("delay", models.CharField(max_length=8)),
                ("staff_count", models.IntegerField()),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DriverImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=100)),
                ("staff_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DutyCardTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duty_card_no", models.CharField(max_length=100)),
                ("route_name", models.CharField(max_length=255)),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=8,
                    ),
                ),
                ("pick_up_time", models.TimeField()),
                ("drop_off_time", models.TimeField()),
                ("shift_time", models.TimeField()),
                ("capacity", models.IntegerField()),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StmRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route_id",
                    models.CharField(db_column="R_id", max_length=50, unique=True),
                ),
                ("route", models.CharField(db_column="Route", max_length=50)),
                ("route_type", models.CharField(db_column="Type", max_length=50)),
                (
                    "operating_days_1",
                    models.CharField(db_column="Operating_days_1", max_length=7),
                ),
                (
                    "operating_days_2",
                    models.CharField(
                        blank=True,
                        db_column="Operating_days_2",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("work_hub", models.CharField(db_column="Work_Hub", max_length=255)),
                (
                    "connection_from",
                    models.CharField(
                        blank=True,
                        db_column="Connection_From",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "connection_to",
                    models.CharField(
                        blank=True, db_column="Connection_To", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Stm_Routes",
            },
        ),
        migrations.CreateModel(
            name="DriverTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_name", models.CharField(max_length=100)),
                ("pick_up_time", models.TimeField()),
                ("drop_off_time", models.TimeField()),
                ("shift_time", models.TimeField()),
                ("head_count", models.IntegerField()),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="inbound",
                        max_length=8,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="duty.driverimportlog",
                    ),
                ),
                (
                    "duty_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="duty.dutycardtrip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StmPickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_id", models.CharField(db_column="Stop_Id", max_length=100)),
                (
                    "pick_up_point",
                    models.CharField(db_column="Pick_Up_Point", max_length=255),
                ),
                (
                    "pick_up_point_order_id",
                    models.IntegerField(db_column="Pick_Up_Point_Order_Id"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        db_column="R_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_points",
                        to="duty.stmroute",
                    ),
                ),
            ],
            options={
                "db_table": "Stm_Pickup_Points",
                "ordering": ["pick_up_point_order_id"],
            },
        ),
        migrations.CreateModel(
            name="StmShiftTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        blank=True, db_column="Time", max_length=50, null=True
                    ),
                ),
                (
                    "special_time",
                    models.TimeField(blank=True, db_column="Special_Time", null=True),
                ),
                (
                    "shift_time",
                    models.TimeField(blank=True, db_column="Shift_time", null=True),
                ),
                ("stop_order", models.PositiveIntegerField(default=0)),
                (
                    "route",
                    models.ForeignKey(
                        db_column="R_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_times",
                        to="duty.stmroute",
                    ),
                ),
            ],
            options={
                "db_table": "Stm_ShiftTime",
                "ordering": ["stop_order", "time"],
            },
        ),
    ]
