# Generated by Django 5.0.7 on 2024-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=100)),
                ("driver_name", models.CharField(max_length=100)),
                ("duty_card_no", models.CharField(max_length=100)),
                ("route_name", models.CharField(max_length=100)),
                ("pick_up_time", models.TimeField()),
                ("drop_off_time", models.TimeField()),
                ("shift_time", models.TimeField()),
                ("head_count", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="trip",
            name="driver",
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.DeleteModel(
            name="Trip",
        ),
    ]
