# Generated by Django 5.0.7 on 2024-12-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delaydata",
            name="date",
            field=models.DateField(),
        ),
    ]
