# Generated by Django 5.0.7 on 2024-07-25 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutycard',
            name='drop_off_time',
        ),
        migrations.RemoveField(
            model_name='dutycard',
            name='head_count',
        ),
        migrations.RemoveField(
            model_name='dutycard',
            name='pick_up_time',
        ),
        migrations.RemoveField(
            model_name='dutycard',
            name='route_name',
        ),
        migrations.RemoveField(
            model_name='dutycard',
            name='shift_time',
        ),
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('pick_up_time', models.TimeField()),
                ('drop_off_time', models.TimeField()),
                ('shift_time', models.TimeField()),
                ('head_count', models.IntegerField()),
                ('duty_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='duty.dutycard')),
            ],
        ),
    ]
