# Generated by Django 5.0.7 on 2024-08-17 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drivertrip",
            name="driver_name",
        ),
        migrations.RemoveField(
            model_name="drivertrip",
            name="duty_card_no",
        ),
        migrations.AddField(
            model_name="drivertrip",
            name="driver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="duty.driverimportlog",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drivertrip",
            name="duty_card",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="duty.dutycardtrip",
            ),
            preserve_default=False,
        ),
    ]
