# Generated by Django 5.0.7 on 2025-03-07 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusMasterList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Bus Number"
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="Capacity")),
            ],
            options={
                "verbose_name": "Bus Master Entry",
                "verbose_name_plural": "Bus Master List",
                "db_table": "bus_master_list",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "db_table": "duty_unit",
            },
        ),
        migrations.AlterField(
            model_name="delaydata",
            name="date",
            field=models.DateField(verbose_name="Date of Delay"),
        ),
        migrations.AlterField(
            model_name="delaydata",
            name="delay",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BusKmTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duty_card_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Duty Card No"
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Submission Date"
                    ),
                ),
                ("bus_no", models.CharField(max_length=20, verbose_name="Bus Number")),
                (
                    "start_km",
                    models.PositiveIntegerField(verbose_name="Start Kilometer"),
                ),
                ("end_km", models.PositiveIntegerField(verbose_name="End Kilometer")),
                (
                    "bus_change",
                    models.BooleanField(
                        default=False, verbose_name="Bus Changed (Optional)"
                    ),
                ),
                (
                    "bus_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Bus Start Time"
                    ),
                ),
                (
                    "bus_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Bus End Time"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Start Time Change (Optional)",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="End Time Change (Optional)"
                    ),
                ),
                (
                    "start_km_change",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Start Kilometer Change (Optional)",
                    ),
                ),
                (
                    "end_km_change",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="End Kilometer Change (Optional)",
                    ),
                ),
                (
                    "changed_bus_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Changed Bus Number",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_km_tracking",
                        to="duty.driverimportlog",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "duty_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_km_tracking",
                        to="duty.dutycardtrip",
                        verbose_name="Duty Card",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EKSTMSalik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salik_start_date", models.DateField()),
                ("salik_satrt_time", models.CharField(max_length=20)),
                ("initial_location", models.CharField(max_length=100)),
                ("salik_end_date", models.DateField()),
                ("salik_end_time", models.CharField(max_length=20)),
                ("final_location", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=20)),
                (
                    "driver_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("crossing_rate", models.CharField(max_length=20)),
                ("routeid", models.CharField(max_length=50)),
                ("routename", models.CharField(max_length=255)),
                ("routetype", models.CharField(max_length=50)),
                ("shift_in", models.CharField(blank=True, max_length=50, null=True)),
                ("shift_out", models.CharField(blank=True, max_length=50, null=True)),
                ("routegroup", models.CharField(max_length=50)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="duty.unit",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "db_table": "EKSTM_salik",
            },
        ),
        migrations.CreateModel(
            name="EKSTMMileage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mileage", models.CharField(max_length=50)),
                ("date", models.DateField()),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="duty.unit",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "db_table": "EKSTM_mileage",
            },
        ),
        migrations.CreateModel(
            name="EKSTMDailyTrips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("routetime", models.CharField(max_length=50)),
                ("shift_out", models.CharField(blank=True, max_length=50, null=True)),
                ("shift_in", models.CharField(blank=True, max_length=50, null=True)),
                ("ride_date", models.DateField()),
                ("first_point", models.CharField(max_length=100)),
                ("route_id", models.CharField(max_length=50)),
                ("route_group", models.CharField(max_length=50)),
                ("route_type", models.CharField(max_length=20)),
                (
                    "driver_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="duty.unit",
                        to_field="code",
                    ),
                ),
            ],
            options={
                "db_table": "EKSTM_daily_trips",
            },
        ),
    ]
