# Generated by Django 5.0.7 on 2024-12-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0002_alter_delaydata_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delaydata",
            options={"ordering": ["-date"], "verbose_name": "Delay Data"},
        ),
    ]
