# Generated by Django 5.0.7 on 2024-08-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_remove_drivertrip_driver_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertrip',
            name='staff_id',
        ),
        migrations.AlterField(
            model_name='driverimportlog',
            name='staff_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dutycardtrip',
            name='duty_card_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
