# Generated by Django 5.0.7 on 2024-07-25 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_remove_dutycard_drop_off_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('pick_up_time', models.TimeField()),
                ('drop_off_time', models.TimeField()),
                ('shift_time', models.TimeField()),
                ('head_count', models.IntegerField()),
                ('duty_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.dutycard')),
            ],
        ),
        migrations.DeleteModel(
            name='TripDetail',
        ),
    ]
