# Generated by Django 5.0.7 on 2025-03-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0002_busmasterlist_unit_alter_delaydata_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ekstmsalik",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="ekstmsalik",
            name="routename",
        ),
        migrations.RemoveField(
            model_name="ekstmsalik",
            name="salik_end_date",
        ),
        migrations.RemoveField(
            model_name="ekstmsalik",
            name="salik_end_time",
        ),
    ]
