# Generated by Django 5.0.7 on 2024-07-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_drivertrip_remove_trip_driver_delete_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
