# Generated by Django 5.0.7 on 2024-12-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0003_alter_delaydata_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delaydata",
            options={},
        ),
        migrations.AlterField(
            model_name="delaydata",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
