# Generated by Django 5.0.7 on 2024-07-26 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0003_trip_delete_tripdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DutyCard',
            new_name='Driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='duty_card',
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='duty.driver'),
            preserve_default=False,
        ),
    ]
