# Generated by Django 5.0.7 on 2025-04-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0003_remove_ekstmsalik_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("mobile_no", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "secondary_contact_no",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("license_no", models.CharField(blank=True, max_length=50, null=True)),
                ("license_issue_date", models.DateField(blank=True, null=True)),
                ("license_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "license_place_of_issue",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "license_front_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "license_back_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("eid_no", models.CharField(blank=True, max_length=50, null=True)),
                ("eid_issue_date", models.DateField(blank=True, null=True)),
                ("eid_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "eid_nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "eid_front_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "eid_back_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("passport_no", models.CharField(blank=True, max_length=50, null=True)),
                ("passport_issue_date", models.DateField(blank=True, null=True)),
                ("passport_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "passport_front_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "passport_back_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="duty.driverimportlog",
                    ),
                ),
            ],
        ),
    ]
