# Generated by Django 5.0.7 on 2024-09-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0003_remove_drivertrip_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverimportlog',
            name='staff_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dutycardtrip',
            name='duty_card_no',
            field=models.CharField(max_length=100),
        ),
    ]
