# Generated by Django 5.0.7 on 2024-07-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0003_driverimportlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverimportlog',
            name='imported_at',
        ),
    ]
