# Generated by Django 5.0.7 on 2024-07-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0004_remove_driverimportlog_imported_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivertrip",
            name="trip_type",
            field=models.CharField(
                choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                default="inbound",
                max_length=8,
            ),
        ),
    ]
