# Generated by Django 5.0.7 on 2024-12-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0004_alter_delaydata_options_alter_delaydata_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delaydata",
            name="date",
            field=models.DateField(verbose_name="Date of Delay"),
        ),
    ]
