# Generated by Django 5.0.7 on 2024-09-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0004_alter_driverimportlog_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutycardtrip',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
