# Generated by Django 5.0.7 on 2025-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0004_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
