# Generated by Django 5.0.7 on 2025-01-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0005_alter_delaydata_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delaydata",
            name="delay",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
