# Generated by Django 5.0.7 on 2024-10-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0005_dutycardtrip_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('route', models.CharField(max_length=255)),
                ('in_out', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=50)),
                ('accident_time', models.TimeField()),
                ('bus_no', models.CharField(max_length=50)),
                ('accident_issue', models.TextField()),
                ('driver_name', models.CharField(max_length=255)),
                ('staff_id', models.CharField(max_length=100)),
                ('staff_count', models.IntegerField()),
                ('replacement_driver', models.CharField(max_length=255)),
                ('replacement_bus', models.CharField(max_length=50)),
                ('report_to_ek', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BreakdownData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('route', models.CharField(max_length=255)),
                ('in_out', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=50)),
                ('breakdown_time', models.TimeField()),
                ('bus_no', models.CharField(max_length=50)),
                ('issue', models.TextField()),
                ('driver_name', models.CharField(max_length=255)),
                ('staff_id', models.CharField(max_length=100)),
                ('staff_count', models.IntegerField()),
                ('replacement_driver', models.CharField(max_length=255)),
                ('replacement_bus', models.CharField(max_length=50)),
                ('report_to_ek', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DelayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('route', models.CharField(max_length=255)),
                ('in_out', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=50)),
                ('std', models.TimeField()),
                ('atd', models.TimeField()),
                ('sta', models.TimeField()),
                ('ata', models.TimeField()),
                ('delay', models.IntegerField()),
                ('staff_count', models.IntegerField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
