# Generated by Django 5.0.7 on 2024-08-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0005_drivertrip_trip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyCardTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_card_no', models.CharField(max_length=100)),
                ('route_name', models.CharField(max_length=255)),
                ('pick_up_time', models.TimeField()),
                ('drop_off_time', models.TimeField()),
            ],
        ),
    ]
