# Generated by Django 5.0.7 on 2024-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0006_accidentsdata_breakdowndata_delaydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentsdata',
            name='Accident_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breakdowndata',
            name='Breakdown_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breakdowndata',
            name='staff_count',
            field=models.IntegerField(max_length=47),
        ),
    ]
