# Generated by Django 5.0.7 on 2025-01-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0006_alter_delaydata_delay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delaydata",
            name="delay",
            field=models.CharField(blank=True, default=1, max_length=5),
            preserve_default=False,
        ),
    ]
