# Generated by Django 5.0.7 on 2025-01-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0007_alter_delaydata_delay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delaydata",
            name="delay",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
