# Generated by Django 5.0.7 on 2024-10-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0008_rename_accident_location_accidentsdata_accident_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccidentsData',
        ),
        migrations.DeleteModel(
            name='BreakdownData',
        ),
        migrations.AlterField(
            model_name='delaydata',
            name='delay',
            field=models.CharField(max_length=8),
        ),
    ]
