# Generated by Django 5.0.7 on 2024-10-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0009_delete_accidentsdata_delete_breakdowndata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_datetime', models.DateTimeField(auto_now_add=True)),
                ('breakdown_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('route_number', models.CharField(max_length=100)),
                ('trip_work_order', models.CharField(max_length=100)),
                ('passengers_involved', models.PositiveIntegerField()),
                ('ek_staff_numbers', models.TextField(blank=True, null=True)),
                ('non_ek_passenger_details', models.TextField(blank=True, null=True)),
                ('injured_passengers', models.PositiveIntegerField(default=0)),
                ('action_taken_for_injured', models.TextField(blank=True, null=True)),
                ('vehicle_damage', models.BooleanField(default=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_id', models.CharField(max_length=100)),
                ('driver_shift', models.CharField(max_length=100)),
                ('breakdown_description', models.TextField()),
                ('ek_vehicles_involved', models.PositiveIntegerField(default=0)),
                ('vehicle_make_plate', models.CharField(max_length=100)),
                ('replacement_vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_to_person', models.CharField(max_length=100)),
                ('reported_datetime', models.DateTimeField()),
            ],
        ),
    ]
