# Generated by Django 5.0.7 on 2025-02-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0008_alter_delaydata_delay"),
        ("duty", "0009_auto_20250202_1828"),
    ]

    operations = []
