# Generated by Django 5.0.7 on 2024-10-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0010_breakdownreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='StmRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(db_column='R_id', max_length=50, unique=True)),
                ('route', models.CharField(db_column='Route', max_length=50)),
                ('route_type', models.CharField(db_column='Type', max_length=50)),
                ('operating_days_1', models.CharField(db_column='Operating_days_1', max_length=7)),
                ('operating_days_2', models.CharField(blank=True, db_column='Operating_days_2', max_length=7, null=True)),
                ('work_hub', models.CharField(db_column='Work_Hub', max_length=255)),
            ],
            options={
                'db_table': 'Stm_Routes',
            },
        ),
        migrations.CreateModel(
            name='StmPickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(db_column='Stop_Id', max_length=100)),
                ('pick_up_point', models.CharField(db_column='Pick_Up_Point', max_length=255)),
                ('route', models.ForeignKey(db_column='R_id', on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='duty.stmroute')),
            ],
            options={
                'db_table': 'Stm_Pickup_Points',
            },
        ),
        migrations.CreateModel(
            name='StmShiftTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('special_time', models.TimeField(blank=True, db_column='Special_Time', null=True)),
                ('shift_time', models.TimeField(blank=True, db_column='Shift_time', null=True)),
                ('route', models.ForeignKey(db_column='R_id', on_delete=django.db.models.deletion.CASCADE, related_name='shift_times', to='duty.stmroute')),
            ],
            options={
                'db_table': 'Stm_ShiftTime',
            },
        ),
    ]
