# Generated by Django 5.0.7 on 2024-10-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0010_breakdownreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=10)),
                ('route_type', models.CharField(max_length=10)),
                ('operating_days', models.CharField(max_length=7)),
                ('work_hub', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=50)),
                ('pick_up_point', models.CharField(max_length=255)),
                ('work_hub', models.CharField(max_length=255)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.route')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_time', models.TimeField()),
                ('pickup_time', models.TimeField()),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.pickuppoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.route')),
            ],
        ),
    ]
