# Generated by Django 5.0.7 on 2025-02-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0010_merge_20250202_2238"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusKmTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_no", models.CharField(max_length=20, verbose_name="Bus Number")),
                (
                    "start_km",
                    models.PositiveIntegerField(verbose_name="Start Kilometer"),
                ),
                ("end_km", models.PositiveIntegerField(verbose_name="End Kilometer")),
                (
                    "bus_change",
                    models.BooleanField(
                        default=False, verbose_name="Bus Changed (Optional)"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Start Time (Optional)"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="End Time (Optional)"
                    ),
                ),
                (
                    "start_km_change",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Start Kilometer (Optional)"
                    ),
                ),
                (
                    "end_km_change",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="End Kilometer (Optional)"
                    ),
                ),
            ],
        ),
    ]
