# Generated by Django 5.0.7 on 2025-03-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0010_merge_20250202_2238"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusMasterList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Bus Number"
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="Capacity")),
            ],
            options={
                "verbose_name": "Bus Master Entry",
                "verbose_name_plural": "Bus Master List",
                "db_table": "bus_master_list",
            },
        ),
        migrations.CreateModel(
            name="BusKmTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duty_card_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Duty Card No"
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Submission Date"
                    ),
                ),
                ("bus_no", models.CharField(max_length=20, verbose_name="Bus Number")),
                (
                    "start_km",
                    models.PositiveIntegerField(verbose_name="Start Kilometer"),
                ),
                ("end_km", models.PositiveIntegerField(verbose_name="End Kilometer")),
                (
                    "bus_change",
                    models.BooleanField(
                        default=False, verbose_name="Bus Changed (Optional)"
                    ),
                ),
                (
                    "bus_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Bus Start Time"
                    ),
                ),
                (
                    "bus_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Bus End Time"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Start Time Change (Optional)",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="End Time Change (Optional)"
                    ),
                ),
                (
                    "start_km_change",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Start Kilometer Change (Optional)",
                    ),
                ),
                (
                    "end_km_change",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="End Kilometer Change (Optional)",
                    ),
                ),
                (
                    "changed_bus_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Changed Bus Number",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_km_tracking",
                        to="duty.driverimportlog",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "duty_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_km_tracking",
                        to="duty.dutycardtrip",
                        verbose_name="Duty Card",
                    ),
                ),
            ],
        ),
    ]
