# Generated by Django 5.0.7 on 2025-02-14 20:XX
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        # Updated dependency to point to the last migration that exists.
        ("duty", "0011_buskmtracking"),
    ]

    operations = [
        # Delete the existing BusKmTracking table (all data will be lost)
        migrations.DeleteModel(
            name="BusKmTracking",
        ),
        # Re-create the BusKmTracking table with the correct schema,
        # including both driver_id and duty_card_id columns.
        migrations.CreateModel(
            name="BusKmTracking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bus_no", models.CharField(max_length=20, verbose_name="Bus Number")),
                ("start_km", models.PositiveIntegerField(verbose_name="Start Kilometer")),
                ("end_km", models.PositiveIntegerField(verbose_name="End Kilometer")),
                ("bus_change", models.BooleanField(default=False, verbose_name="Bus Changed (Optional)")),
                ("start_time", models.TimeField(null=True, blank=True, verbose_name="Start Time (Optional)")),
                ("end_time", models.TimeField(null=True, blank=True, verbose_name="End Time (Optional)")),
                ("start_km_change", models.PositiveIntegerField(null=True, blank=True, verbose_name="Start Kilometer (Optional)")),
                ("end_km_change", models.PositiveIntegerField(null=True, blank=True, verbose_name="End Kilometer (Optional)")),
                (
                    "duty_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_km_tracking",
                        to="duty.DutyCardTrip",
                        verbose_name="Duty Card",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_km_tracking",
                        to="duty.DriverImportLog",
                        verbose_name="Driver",
                    ),
                ),
            ],
        ),
    ]
