# Generated by Django 5.0.7 on 2024-10-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0011_route_pickuppoint_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='operating_days',
            new_name='operating_days_1',
        ),
        migrations.AddField(
            model_name='route',
            name='operating_days_2',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
