# Generated by Django 5.0.7 on 2024-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0011_stmroute_stmpickuppoint_stmshifttime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stmshifttime',
            options={'ordering': ['stop_order', 'time']},
        ),
        migrations.AddField(
            model_name='stmshifttime',
            name='stop_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stmshifttime',
            name='time',
            field=models.CharField(blank=True, db_column='Time', max_length=50, null=True),
        ),
    ]
