# Generated by Django 5.0.7 on 2024-10-25 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0012_rename_operating_days_route_operating_days_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='duty.route'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='stop_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='duty.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='duty.route'),
        ),
    ]
