# Generated by Django 5.0.7 on 2024-11-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0012_alter_stmshifttime_options_stmshifttime_stop_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stmpickuppoint',
            options={'ordering': ['pick_up_point_order_id']},
        ),
        migrations.AddField(
            model_name='stmpickuppoint',
            name='pick_up_point_order_id',
            field=models.IntegerField(db_column='Pick_Up_Point_Order_Id', default=1),
            preserve_default=False,
        ),
    ]
