# Generated by Django 5.0.7 on 2025-02-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0012_recreate_buskmtracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="buskmtracking",
            name="bus_end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="End Time"),
        ),
        migrations.AddField(
            model_name="buskmtracking",
            name="bus_start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Start Time"),
        ),
        migrations.AlterField(
            model_name="buskmtracking",
            name="end_km_change",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="End Kilometer Change (Optional)"
            ),
        ),
        migrations.AlterField(
            model_name="buskmtracking",
            name="end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="End Time Change (Optional)"
            ),
        ),
        migrations.AlterField(
            model_name="buskmtracking",
            name="start_km_change",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Start Kilometer Change (Optional)"
            ),
        ),
        migrations.AlterField(
            model_name="buskmtracking",
            name="start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Start Time Change (Optional)"
            ),
        ),
    ]
