# Generated by Django 5.0.7 on 2024-11-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0013_alter_stmpickuppoint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutycardtrip',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
