# Generated by Django 5.0.7 on 2025-02-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0013_buskmtracking_bus_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buskmtracking",
            name="duty_card_no",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Duty Card No"
            ),
        ),
    ]
