# Generated by Django 5.0.7 on 2024-10-26 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0013_alter_pickuppoint_route_alter_pickuppoint_stop_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StmRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(db_column='R_id', max_length=50, unique=True)),
                ('route', models.CharField(max_length=50)),
                ('route_type', models.CharField(max_length=50)),
                ('operating_days_1', models.CharField(max_length=7)),
                ('operating_days_2', models.CharField(blank=True, max_length=7, null=True)),
                ('work_hub', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Stm_Routes',
            },
        ),
        migrations.RemoveField(
            model_name='shift',
            name='pickup_point',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='route',
        ),
        migrations.CreateModel(
            name='StmPickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=50)),
                ('pick_up_point', models.CharField(max_length=255)),
                ('route', models.ForeignKey(db_column='R_id', on_delete=django.db.models.deletion.CASCADE, to='duty.stmroute')),
            ],
            options={
                'db_table': 'Stm_Pickup_Points',
            },
        ),
        migrations.CreateModel(
            name='StmShiftTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('special_time', models.TimeField(blank=True, null=True)),
                ('shift_time', models.TimeField()),
                ('route', models.ForeignKey(db_column='R_id', on_delete=django.db.models.deletion.CASCADE, to='duty.stmroute')),
            ],
            options={
                'db_table': 'Stm_ShiftTime',
            },
        ),
        migrations.DeleteModel(
            name='PickupPoint',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
