# Generated by Django 5.0.7 on 2025-02-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0014_buskmtracking_duty_card_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="buskmtracking",
            name="submission_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Submission Date"
            ),
        ),
    ]
