# Generated by Django 5.0.7 on 2024-10-26 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0014_stmroute_remove_shift_pickup_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stmshifttime',
            name='pickup_point',
            field=models.ForeignKey(db_column='Stop_Id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_times', to='duty.stmpickuppoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stmpickuppoint',
            name='route',
            field=models.ForeignKey(db_column='R_id', on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='duty.stmroute'),
        ),
        migrations.AlterField(
            model_name='stmroute',
            name='route_type',
            field=models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stmshifttime',
            name='route',
            field=models.ForeignKey(db_column='R_id', on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='duty.stmroute'),
        ),
    ]
