# Generated by Django 5.0.7 on 2025-02-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0015_buskmtracking_submission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buskmtracking",
            name="bus_end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Bus End Time"),
        ),
        migrations.AlterField(
            model_name="buskmtracking",
            name="bus_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Bus Start Time"
            ),
        ),
    ]
