# Generated by Django 5.0.7 on 2024-10-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0015_stmshifttime_pickup_point_alter_stmpickuppoint_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmroute',
            name='operating_days_1',
            field=models.CharField(db_column='Operating_days_1', max_length=7),
        ),
        migrations.AlterField(
            model_name='stmroute',
            name='operating_days_2',
            field=models.CharField(blank=True, db_column='Operating_days_2', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='stmroute',
            name='route',
            field=models.CharField(db_column='Route', max_length=50),
        ),
        migrations.AlterField(
            model_name='stmroute',
            name='route_type',
            field=models.CharField(db_column='Type', max_length=50),
        ),
        migrations.AlterField(
            model_name='stmroute',
            name='work_hub',
            field=models.CharField(db_column='Work_Hub', max_length=255),
        ),
    ]
