# Generated by Django 5.0.7 on 2024-11-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0015_stmpickuppoint_connection_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stmpickuppoint',
            name='connection_from',
        ),
        migrations.RemoveField(
            model_name='stmpickuppoint',
            name='connection_to',
        ),
        migrations.AddField(
            model_name='stmroute',
            name='connection_from',
            field=models.CharField(blank=True, db_column='Connection_From', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stmroute',
            name='connection_to',
            field=models.CharField(blank=True, db_column='Connection_To', max_length=255, null=True),
        ),
    ]
