# Generated by Django 5.0.7 on 2024-10-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0016_alter_stmroute_operating_days_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmpickuppoint',
            name='pick_up_point',
            field=models.CharField(db_column='Pick_Up_Point', max_length=255),
        ),
        migrations.AlterField(
            model_name='stmpickuppoint',
            name='stop_id',
            field=models.CharField(db_column='Stop_Id', max_length=50),
        ),
    ]
