# Generated by Django 5.0.7 on 2025-02-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0016_alter_buskmtracking_bus_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buskmtracking",
            name="changed_bus_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Changed Bus Number"
            ),
        ),
    ]
