# Generated by Django 5.0.7 on 2024-11-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0016_remove_stmpickuppoint_connection_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=100, unique=True)),
                ('seat_capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
