# Generated by Django 5.0.7 on 2024-10-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0017_alter_stmpickuppoint_pick_up_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stmpickuppoint',
            name='route',
        ),
        migrations.AddField(
            model_name='stmpickuppoint',
            name='r_id',
            field=models.CharField(db_column='R_id', default=1, max_length=50),
            preserve_default=False,
        ),
    ]
