# Generated by Django 5.0.7 on 2025-02-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duty", "0017_buskmtracking_changed_bus_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusMasterList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Bus Number"
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="Capacity")),
            ],
            options={
                "verbose_name": "Bus Master Entry",
                "verbose_name_plural": "Bus Master List",
                "db_table": "bus_master_list",
            },
        ),
    ]
