# Generated by Django 5.0.7 on 2024-10-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0018_remove_stmpickuppoint_route_stmpickuppoint_r_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stmpickuppoint',
            name='pick_up_point',
        ),
        migrations.RemoveField(
            model_name='stmpickuppoint',
            name='r_id',
        ),
        migrations.RemoveField(
            model_name='stmpickuppoint',
            name='stop_id',
        ),
        migrations.AlterModelTable(
            name='stmpickuppoint',
            table=None,
        ),
        migrations.AddField(
            model_name='stmpickuppoint',
            name='Pick_Up_Point',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stmpickuppoint',
            name='R_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stmpickuppoint',
            name='Stop_Id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
