# Generated by Django 5.0.7 on 2024-12-08 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0018_triplog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triplog',
            name='driver',
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='bus_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='seat_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='triplog',
            name='scanned_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='triplog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShiftDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_km', models.FloatField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.busdetails')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('duty_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.dutycardtrip')),
            ],
        ),
        migrations.AddField(
            model_name='triplog',
            name='shift_duty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='duty.shiftduty'),
            preserve_default=False,
        ),
    ]
