# Generated by Django 5.0.7 on 2024-12-15 05:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0019_remove_triplog_driver_alter_busdetails_bus_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftduty',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='shiftduty',
            name='duty_card',
        ),
        migrations.RemoveField(
            model_name='triplog',
            name='shift_duty',
        ),
        migrations.AddField(
            model_name='shiftduty',
            name='duty_card_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triplog',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triplog',
            name='scanned_staff_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='bus_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shiftduty',
            name='start_km',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='triplog',
            name='scanned_ids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triplog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
