# Generated by Django 5.0.7 on 2024-10-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0019_remove_stmpickuppoint_pick_up_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmpickuppoint',
            name='R_id',
            field=models.CharField(max_length=100),
        ),
    ]
