# Generated by Django 5.0.7 on 2024-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0020_alter_stmpickuppoint_r_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stmshifttime',
            options={'verbose_name': 'Shift Time', 'verbose_name_plural': 'Shift Times'},
        ),
        migrations.RenameField(
            model_name='stmshifttime',
            old_name='shift_time',
            new_name='Shift_time',
        ),
        migrations.RenameField(
            model_name='stmshifttime',
            old_name='special_time',
            new_name='Special_Time',
        ),
        migrations.RenameField(
            model_name='stmshifttime',
            old_name='time',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='stmshifttime',
            name='pickup_point',
        ),
        migrations.RemoveField(
            model_name='stmshifttime',
            name='route',
        ),
        migrations.AddField(
            model_name='stmshifttime',
            name='R_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='stmshifttime',
            table='stm_shift_time',
        ),
    ]
