# Generated by Django 5.0.7 on 2024-10-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0021_alter_stmshifttime_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmshifttime',
            name='R_id',
            field=models.CharField(max_length=100),
        ),
    ]
