# Generated by Django 5.0.7 on 2024-10-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0022_alter_stmshifttime_r_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stmshifttime',
            options={},
        ),
        migrations.AlterField(
            model_name='stmshifttime',
            name='R_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stmshifttime',
            name='Shift_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stmshifttime',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='stmshifttime',
            table=None,
        ),
    ]
