# Generated by Django 5.0.7 on 2024-10-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0024_alter_stmshifttime_r_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmshifttime',
            name='Shift_time',
            field=models.TimeField(blank=True, db_column='Shift_time', null=True),
        ),
        migrations.RenameField(
            model_name='stmshifttime',
            old_name='Shift_time',
            new_name='shift_time',
        ),
        migrations.AlterField(
            model_name='stmshifttime',
            name='Special_Time',
            field=models.TimeField(blank=True, db_column='Special_Time', null=True),
        ),
        migrations.RenameField(
            model_name='stmshifttime',
            old_name='Special_Time',
            new_name='special_time',
        ),
        migrations.AlterField(
            model_name='stmshifttime',
            name='Time',
            field=models.TimeField(blank=True, db_column='Time', null=True),
        ),
        migrations.RenameField(
            model_name='stmshifttime',
            old_name='Time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='stmshifttime',
            name='R_id',
        ),
        migrations.AddField(
            model_name='stmshifttime',
            name='route',
            field=models.ForeignKey(db_column='R_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_times', to='duty.stmroute'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='stmshifttime',
            table='Stm_ShiftTime',
        ),
    ]
