# Generated by Django 5.0.7 on 2024-10-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0025_alter_stmshifttime_shift_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stmshifttime',
            name='route',
        ),
        migrations.RemoveField(
            model_name='stmshifttime',
            name='shift_time',
        ),
        migrations.RemoveField(
            model_name='stmshifttime',
            name='special_time',
        ),
        migrations.RemoveField(
            model_name='stmshifttime',
            name='time',
        ),
        migrations.AddField(
            model_name='stmshifttime',
            name='R_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='stmshifttime',
            table=None,
        ),
        migrations.AddField(
            model_name='stmshifttime',
            name='Shift_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stmshifttime',
            name='Special_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stmshifttime',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
